### ISSUE TITLE
i18n from Markus

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#102]
[language.zip](https://github.com/halfbrained/cuda_lsp/files/6911318/language.zip)

```
Attached is the updated translation for the updated plugin.LSP_Client in
Misc-de_AT.

In language.py I changed line 697 in order to include 'NOTE: ' into the
translation:
print(_('NOTE: {}: {} - file does not exist: {!r}, uri:{!r}')

See line 227:
print(_('NOTE: {}: {} - Failed to connect on port {}') 
```

**Comment by Alexey-T** [comment]
corrected version from him.
[language2.zip](https://github.com/halfbrained/cuda_lsp/files/6911372/language2.zip)

**Comment by halfbrained** [comment]
hm... will Console highlight "NOTE:" in other languages? (is it magical? :) )

**Comment by Alexey-T** [comment]
I said to M that we need fixed 'NOTE: ' and he had updated the file.

**Comment by halfbrained** [comment]
applied
