### ISSUE TITLE
Error with typescript-language-server

### ISSUE THREAD

**Issue by eltonfabricio10** [halfbrained/cuda_lsp#105]
ResponseError[-32603]: Request initialize failed with message: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

**Comment by Alexey-T** [comment]
We need the sample Typescript file, and position (line: column) where you call auto-completion. (did you do auto-completion? other thing?)

**Comment by eltonfabricio10** [comment]
Sorry, my error
