### ISSUE TITLE
PyLS: type 'keyword' for many non-keyword items

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#115]
file dlg.py from cuda_lsp.
![Screenshot from 2022-05-19 10-21-04](https://user-images.githubusercontent.com/4154978/169235800-6493aef5-1318-4e78-b98b-24cee3b7651f.png)

![Screenshot from 2022-05-19 10-20-53](https://user-images.githubusercontent.com/4154978/169235817-ea4024cf-52bc-4d09-b32d-c4834f4bea51.png)

![Screenshot from 2022-05-19 10-20-44](https://user-images.githubusercontent.com/4154978/169235832-e803000e-11c7-4c47-b70b-616644cdcaa1.png)

type 'keyword' for many IDs which are not keywords!

lsp_py.json
```
{
    "lexers": {
      "Python": "python"
    },
    "cmd_unix": ["~/.local/bin/pyls"],
    "log_stderr": true    
}
```
Ubuntu 20.

@veksha do you use this server?

**Comment by veksha** [comment]
i'm using `pylsp.exe`, not `pyls.exe`
can't see problem on my side with pylsp.

**Comment by Alexey-T** [comment]
ok, it's server issue.

**Comment by veksha** [comment]
https://github.com/palantir/python-language-server/issues/840

this issue is known but:

> The palantir python-language-server (pyls) is unmaintained; a maintained fork is the python-lsp-server (pylsp) project; you can install it with pip via: pip install python-lsp-server

also new client-side filtering of cuda_lsp is case sensitive. is it ok?

**Comment by Alexey-T** [comment]
Thanks. yes, it is ok.

**Comment by Alexey-T** [comment]
wiki edited!
