### ISSUE TITLE
Problem with bash-language-server

### ISSUE THREAD

**Issue by eltonfabricio10** [halfbrained/cuda_lsp#116]
What is this message?

![Screenshot_20220915_133609](https://user-images.githubusercontent.com/25956396/190460891-71967602-307c-48a7-8340-5b45a45b3c07.png)

My config file: `~/.config/cudatext/settings/lsp_bash.json`

```
{
    "lexers": {
        "Bash script": "bash"
    },
    "cmd_unix": ["/usr/sbin/bash-language-server", "start"]
}
```

**Comment by Alexey-T** [comment]
I think it is server-specific message. 

- do you see this msg in other editors with LSP?
- can you ask from LSP server authors?

@veksha may be interested.

**Comment by veksha** [comment]
please see PR.

**Comment by Alexey-T** [comment]
applied PR.

**Comment by veksha** [comment]
Hi @eltonfabricio10.
is it working for you now?

**Comment by eltonfabricio10** [comment]
Partially... 
I think it should work like ST

**Comment by Alexey-T** [comment]
But what is not working like in ST? what issue do you have.

**Comment by eltonfabricio10** [comment]
https://github.com/CudaText-addons/cuda_lsp/pull/20#issuecomment-1248760171

With this log message

**Comment by Alexey-T** [comment]
Elton, what this animation tells us? I don't get it

**Comment by eltonfabricio10** [comment]
I updated lsp plugin. It's OK now
