### ISSUE TITLE
Bash: completion inserts 'rmdir()'

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#117]
On ubuntu i see ok completions. 

![Screenshot from 2022-09-16 03-01-50](https://user-images.githubusercontent.com/4154978/190528969-a865dbdd-fb81-451b-a1bc-16ca8f4f9934.png)

but cmd names are inserted with `()`:
eg `rmdir()`.
@veksha

**Comment by veksha** [comment]
also if I press ctrl+space on empty line and choose something - no text will be added.

**Comment by Alexey-T** [comment]
Yes, confirmed it

**Comment by veksha** [comment]
> but cmd names are inserted with `()`:

Sublime has support for "completion snippets", therefore it doesn't insert `()` manually.
It relies on lsp-server snippet text.

For CudaText `snippetSupport` is set to `False`, so Cuda_LSP is manually inserting `()` based on "completion item kind" (i.e. if function/method then insert `()`)

I enabled support for snippets format (simply set `snippetSupport` to `True` in CAPABILITIES)
https://github.com/CudaText-addons/cuda_lsp/pull/21

now we can get `func()` text from server, (no need to manually insert parentheses)
but snippets could be not just plain text, it could be a lot more then simple text.
I don't know anything about it yet, but I created this draft PR so we can test it and see how it behaves with different lsp-servers.

**Comment by veksha** [comment]
maybe you, @Alexey-T , know something about this snippet format:

![image](https://user-images.githubusercontent.com/275333/190712848-af3e627a-7fd4-47ba-a98f-2347a614df22.png)

**Comment by veksha** [comment]
I see that for bash it now doesn't insert `()`, _(like in Sublime)_
for clangd it inserts `()` _(like in Sublime)_
for python it doesn't insert `()` _(like in Sublime)_

**Comment by Alexey-T** [comment]
Yes I know about this snip-format. we use it (almost it) in Snippets plug.
And you cannot just insert snippets text for any complex snippet, if it has tabstops.

https://wiki.freepascal.org/CudaText_plugins#Format_of_snippet_files

**Comment by Alexey-T** [comment]
If  you got from server snippet-text with tabstops (find `${` ) then we are in bad situation

**Comment by veksha** [comment]
We need lsp-server that will provide us with complex snippets, so we can test it.

**Comment by Alexey-T** [comment]
Can we ask (the detailed question) at https://github.com/sublimelsp/LSP/issues ?

**Comment by veksha** [comment]
code from sublimelsp:
```python
        if item.get("insertTextFormat", InsertTextFormat.PlainText) == InsertTextFormat.Snippet:
            self.view.run_command("insert_snippet", {"contents": new_text})
        else:
            self.view.run_command("insert", {"characters": new_text})
```
as you can see Sublime Text have internal command "insert_snippet" which is inside closed sources.

**Comment by Alexey-T** [comment]
We have 'insert-snippet' code in open source! can you grab it from Snippets plugin?

**Comment by veksha** [comment]
OK

**Comment by eltonfabricio10** [comment]
This is interesting!

![Peek 16-09-2022 20-42](https://user-images.githubusercontent.com/25956396/190831041-93fdfd14-a40a-4fea-90a4-6a19be80ee87.gif)

**Comment by veksha** [comment]
@eltonfabricio10 do you have another completion addon enabled? or only Cuda_lsp? maybe snippets addon?

**Comment by eltonfabricio10** [comment]
Cuda_lsp and complete_from_text(lexers=-,ini files,markdown,restructuredtext,properties,bash script)

I removed lexer bash from complete_from_text... 
Now it's working as I want...
Sorry for my wrong configuration.

**Comment by Alexey-T** [comment]
@veksha Bug is reproducible

- new line, type 'd', ctrl+space
- in listbox press Left, then choose any item. eg "deluser"
--> `deluser()d`

**Comment by Alexey-T** [comment]
@veksha No, that was a plugin bug, see #120 .

If you see 'warnings' instead of 'errors' - it is Shellcheck issue! please report to them. maybe Windows version differs from Linux?

Sample bash file giving 'errors' for me
```
#/bin/sh
cp -rf $from/data $app/Contents/Resources
cp -rf $from/settings_default $app/Contents/Resources

mkdir $app/Contents/Resources/py/cuda_comments
[[sdfsdf 343 --:::
] [[[sdfsdf #$#$ #$#$mkdir $app/Contents/Resources/py/cuda_new_file
)) (sdfsdf #$#$ #$#$mkdir $app/Contents/Resources/py/cuda_new_file
zdf
```

**Comment by veksha** [comment]
> If you see 'warnings' instead of 'errors' - it is Shellcheck issue! please report to them. maybe Windows version differs from Linux?

I see errors now! just not for "zdf" kind of lines.
I don't see a lot of keywords like "rm", "rmdir", (etc) in the list.
it's issue of server.

**Comment by veksha** [comment]
> but cmd names are inserted with `()`:
> eg `rmdir()`.

with snippetSupport branch merged parentheses will be inserted by lsp-server, not by lsp-client.
so this issue can now be closed.
