### ISSUE TITLE
Cud LSP 'editor' control is not refreshed/repainted

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#118]
...after I edit file and new gutter-icon appeared. I click the LSP editor and its repainted!

`ed.action(EDACTION_UPDATE)` can help?
Linux. Bash server

@veksha

**Comment by Alexey-T** [comment]
![Screenshot from 2022-09-16 03-21-36](https://user-images.githubusercontent.com/4154978/190530731-b93f41c4-522e-48b1-ab1f-db600f772c9e.png)

**Comment by veksha** [comment]
can you reproduce it again and again?
(does it happen when you select another tab?)

**Comment by Alexey-T** [comment]
fixed. added `cmd_RepaintEditor`.
