### ISSUE TITLE
'goto ref's' is giving too small info

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#12]
![Screenshot from 2021-04-10 20-33-41](https://user-images.githubusercontent.com/4154978/114279196-1e2e5400-9a3c-11eb-8d82-4fd20564a84d.png)
can you show 'source file line' after the '\t' in items?

**Comment by Alexey-T** [comment]
dlg_menu(MENU_LIST_ALT)

**Comment by Alexey-T** [comment]
and here too!
![Screenshot from 2021-04-10 20-36-06](https://user-images.githubusercontent.com/4154978/114279261-65b4e000-9a3c-11eb-9d56-26e4dcb7c62e.png)

**Comment by halfbrained** [comment]
changed

![ref-issue12](https://user-images.githubusercontent.com/74829192/114297044-1790f280-9ab7-11eb-9e4a-eb0a1db9e612.png)
