### ISSUE TITLE
bug with autocomplete insertion with Left key

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#120]
@veksha Bug is reproducible (Bash server)

-    new line, type 'd', ctrl+space
-    in listbox press Left, then choose any item. eg "deluser"
--> deluser()d

**Comment by veksha** [comment]
it happens only on "0" caret pos.
fixed. please see PR

**Comment by veksha** [comment]
works?

**Comment by Alexey-T** [comment]
yes, Tks.
