### ISSUE TITLE
Auto-scroll for log messages

### ISSUE THREAD

**Issue by eltonfabricio10** [halfbrained/cuda_lsp#121]
It's possible? @veksha

**Comment by CudaText-addons** [comment]
@veksha @eltonfabricio10 I enabled 'issues' at https://github.com/CudaText-addons/cuda_lsp/issues , let't use it

**Comment by veksha** [comment]
@Alexey-T, please see draft PR and read description:
https://github.com/CudaText-addons/cuda_lsp/pull/27

**Comment by CudaText-addons** [comment]
applied the PR.
