### ISSUE TITLE
when 'go to definition' works it does NOT scroll to caret-line (if file has history saved)

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#14]
ed.set_prop(PROP_LINE_TOP, max(0, n-3))

**Comment by halfbrained** [comment]
> ed.set_prop(PROP_LINE_TOP, max(0, n-3))

Since it doesn't work, is there a better way than this?

``` python
        ed.set_caret(targetrange.start.character, targetrange.start.line) # goto specified position start
        ed.set_prop(PROP_LINE_TOP, max(0, targetrange.start.line-3))
```

Command "scroll to top caret" also fails me in this case

**Comment by Alexey-T** [comment]
let's find why it don't work! can you give repro in Console or in small plg?

**Comment by halfbrained** [comment]
Currently `PROP_LINE_TOP` is being set after opening file, like in your first comment. It doesn't work for you (this issue), so you have a repro :)

Do you still need a small repro? If so - I'll make it

**Comment by Alexey-T** [comment]
at the end of `do_goto`

```
        targetpath = uri_to_path(uri)
        file_open(targetpath)
        app_idle(True) #####
        ed.set_caret(targetrange.start.character, targetrange.start.line) # goto specified position start
        ed.set_prop(PROP_LINE_TOP, max(0, targetrange.start.line-3))
```

**Comment by halfbrained** [comment]
Works now. That's good to know, thanks.

fixed
