### ISSUE TITLE
require that lspconfig/* files have the extension .json

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#16]
it will force users to have json lexer.

**Comment by halfbrained** [comment]
changed

**Comment by Alexey-T** [comment]
can you require .json too? so that 'readme.txt" or 'mynotes' will be ignored?

**Comment by halfbrained** [comment]
Already do

https://github.com/halfbrained/cuda_lsp/blob/364a76b6d4219841874d71abe9775ac2fcf6d5e0/lsp.py#L446-L450
