### ISSUE TITLE
hover tooltip needs some limiting by X/Y coord

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#18]
![aa](https://user-images.githubusercontent.com/4154978/114279553-ede7b500-9a3d-11eb-8e6e-87fb5c5a7e9d.png)

**Comment by halfbrained** [comment]
changed

![hover_fix](https://user-images.githubusercontent.com/74829192/114301708-b07f3800-9ace-11eb-8a71-707cceba5bcd.png)
