### ISSUE TITLE
wish list: show 'go to definition' link directly in hover-form

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#21]
e.g. on the top of hover-form we can place (underlined) blue hyperlink like "file.py:20" which can be clicked in this hover form.

**Comment by Alexey-T** [comment]
dlg_proc control "linklabel": label which activates URL on click.

**Comment by halfbrained** [comment]
I would need to make another request to server to get location of the definition, so I would like to avoid that...

Would something like this be ok? 

[goto:Definition](https://github.com)

And it probably would be ok to automatically go to the definition (without a dialog) when there only one, right?

**Comment by Alexey-T** [comment]
yes, yes.

**Comment by halfbrained** [comment]
Links don't seem to work in the hover dialog. Even html urls - they are colored blue and underlined, but double-clicking does nothing, and when hovering over link - cursor is "over text" type, and not "over something clickable".

These change nothing:
* PROP_RO True or False
* ed.action(EDACTION_UPDATE, 1) after changing text
* Not changing PROP_LINKS_REGEX

``` Python
>>> Hint.ed.get_prop(PROP_LINKS_CLICKS)
2
>>> Hint.ed.get_prop(PROP_LINKS_SHOW)
True
```

**Comment by Alexey-T** [comment]
Links in editor-- maybe it's a bug, if you can please file a report with a demo

I meaned that u place 2nd control in the hover-form, control "label_link" or a button.

**Comment by halfbrained** [comment]
created an issus https://github.com/Alexey-T/CudaText/issues/3315

**Comment by halfbrained** [comment]
added

![goto_def_btn](https://user-images.githubusercontent.com/74829192/114587232-21208300-9c8e-11eb-8c49-e1328850b706.png)
