### ISSUE TITLE
avoid f-strings again, pls

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#23]

**Comment by halfbrained** [comment]
Because of dependencies this plugin probably won't run on Python prior to 3.6, so there shouldn't be any problems? Or remove them anyway? :)

**Comment by Alexey-T** [comment]
not 'anyway' of coz. we need error msgbox if plugin runs in 3.5-.

**Comment by halfbrained** [comment]
I'll try to make it work on older versions later, if that works out - will remove f-strings.
