### ISSUE TITLE
maybe plugin misses some on_mouse_stop events?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#26]
когда я в одной строке вожу по Id влево, вправо (быстро чтобы плагин подавился) то получается так двигать чтобы один из "стопов" ничего не дал. как будто ивент пропустился.

**Comment by Alexey-T** [comment]
[vokoscreenNG-2021-04-10_22-03-52.zip](https://github.com/halfbrained/cuda_lsp/files/6290568/vokoscreenNG-2021-04-10_22-03-52.zip)

**Comment by halfbrained** [comment]
https://github.com/halfbrained/cuda_lsp/blob/a925c3f9bafdc3f161238610cdc5208527d337c7/lsp.py#L213-L215

Я пропускаю ивент когда диалог уже показан. Кажется сделал так, чтобы избежать `on_mouse_stop` ивентов, когда курсор в области диалога...

Сейчас подругому сделаю и посмотрю что будет :)

Кстати, можно как-то избежать этого ивента когда я в главном меню? Очень неуместно :)

**Comment by Alexey-T** [comment]
да, я тоже заметил про меню. To fix.

**Comment by halfbrained** [comment]
починил, теперь проверяю в форме ли диалога курсор, кажется проблем нет
