### ISSUE TITLE
broken result of autocompletion Enter

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#29]
line

            msg_status(msg + _("Cannot format selection(s)"))

call completion after "msg",choose"msg_box". result is bad str.

            msg_box(text, flags)(msg + _("Cannot format selection(s)"))

**Comment by halfbrained** [comment]
The result with parenthesis is according to the specification, but I should probably use just textual part like Sublime does...

**Comment by halfbrained** [comment]
I got confused at some point reading the spec :D 

fixed now
