### ISSUE TITLE
wrong server replies-- after Undo?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#30]
after #29, i did some completion Enter, then Undo. 2-3 times.
 then server does this crap

![bb](https://user-images.githubusercontent.com/4154978/114284922-02d34100-9a5c-11eb-92c0-c7186182642b.png)

**Comment by Alexey-T** [comment]
after file close+ open -- server works OK.

**Comment by halfbrained** [comment]
found the problem - `\n` - this bastard... fixing

**Comment by halfbrained** [comment]
fixed
