### ISSUE TITLE
how to show 'go to ref' window

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#31]
https://user-images.githubusercontent.com/74829192/114297044-1790f280-9ab7-11eb-9e4a-eb0a1db9e612.png

I sugest to show this
```
filename.py, line 202
    /path/of/dir1
file2.py, line 303
    /path/of/dir2
```

**Comment by Alexey-T** [comment]
like here +++ line numbers in 1st line
![Screenshot from 2021-04-11 13-12-07](https://user-images.githubusercontent.com/4154978/114300167-91c97300-9ac7-11eb-8a8d-638ffa994d18.png)

**Comment by halfbrained** [comment]
changed (https://github.com/halfbrained/cuda_lsp/commit/9dc297b0390c0cff6dcb591cdfa2e3370f096d27)

![gotos_2](https://user-images.githubusercontent.com/74829192/114302470-d823cf80-9ad1-11eb-9df9-180b1e1152fd.png)
