### ISSUE TITLE
autocompletion- inserted 'app_idle' bad

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#34]
must insert this

    app_idle(|)

but it does

    app_idle(wait)|

**Comment by Alexey-T** [comment]
now it inserts

    app_idle

but we need `(` after it and `)` will be good

**Comment by halfbrained** [comment]
I'm enabling this for methods, functions, contructors and classes. I'm not 100% about the last two, so any guidance on this matter is welcome.

**Comment by halfbrained** [comment]
added
