### ISSUE TITLE
if plg runs on older Python 3.5-, show some msgbox and avoid all working w/o raising exception

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#37]

**Comment by halfbrained** [comment]
added ([code](https://github.com/halfbrained/cuda_lsp/commit/5cc1be615c1630e34fa76dadbd2e3eb149f46f81#diff-3d750e5f9aeb02fe9640bafa639c40e688d59e618a194fe9c9258320b533bdabR532-R543))

**Comment by Alexey-T** [comment]
if ver.major < 3 or ver.minor < 5:

-->
if (ver,major, ver.minor) < (3, 5)
@halfbrained

**Comment by Alexey-T** [comment]
callback = lambda *args, msg=msg, **vargs: msg_box(msg, MB_OK or MB_ICONWARNING)

@halfbrained

**Comment by halfbrained** [comment]
thanks, changed
