### ISSUE TITLE
maybe need an option for height of hover-form in lines

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#39]
10 default  is ok.

**Comment by halfbrained** [comment]
added

![max_lines](https://user-images.githubusercontent.com/74829192/114669550-b1041280-9d0a-11eb-989f-1042b5536610.png)

**Comment by Alexey-T** [comment]
@halfbrained do we have all options documented? readme or commentes in default cfg.

**Comment by halfbrained** [comment]
> (comments in cfg is bad- JSON don't allow comments, but Cud allows them)

But it is still much better than having options and their description in two different places :) ...but yes, it seems that I cant add options to json with comments, so I will probably move descriptions to readme, if there is no better way.

Just had an idea, I tried to open config + readme in a floating group (something like Sublime does). But this:
```
file_open((f0, f1), group=6)
```
 opens files-tab in the main window even when floating group is already exists.
I this a bug? Is this a good idea? :)

**Comment by Alexey-T** [comment]
last Cud beta had a fix for that. do you have the last one? IF the float-group is opened before file_open call, file_open will open in gr6. only if it's opened.

**Comment by Alexey-T** [comment]
to open the float-grp, u need to call a command from cudatext_cmd.py
