### ISSUE TITLE
maybe move 'sansio_lsp_client' to 'lsp_modules' too?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#41]

**Comment by halfbrained** [comment]
I could... if I was into chaos!

'lsp_modules' - these you can update or delete (system install will be used) with no problems.
'sansio_lsp_client' - heavily modified and very far from the original module

although ... most people wouldn't care, so if you think that would be better - I will

**Comment by Alexey-T** [comment]
OK so, don't move
