### ISSUE TITLE
we need the option to specify several lexer names per one server

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#43]
eg for HTML server users may need to set N lexers for 1 server: 

HTML
PHP
and
![Screenshot from 2021-04-13 00-49-42](https://user-images.githubusercontent.com/4154978/114467150-27f9b800-9bf2-11eb-8c36-edb792419fbe.png)

so lang_ids is not needed, let user write this mapping!
```
lang_ids = {
    'ABAP': 'abap',
    'Windows Bat': 'bat',
    'Batch files': 'bat',
    'BibTeX': 'bibtex',
    'Clojure': 'clojure',
    'Coffeescript': 'coffeescript',
    'C': 'c',
    'C++': 'cpp',
    'C#': 'csharp',
```

**Comment by Alexey-T** [comment]
it can be 
```
{
    "lexers": ["HTML aa", "HTML bb", "HTML more"],
    "server_lang": "html",
    "cmd": ["/home/user/path"]
}
```

**Comment by halfbrained** [comment]
I can do that, but for servers with multiple language ids (e.g. C,C++) you will need to create config file for each lang_id, since I am required to give  lang_id of the document to server.

The other way - user adds mapping of 'lexer_name -> lang_id' somewhere

**Comment by Alexey-T** [comment]
it is Ok if users need to create 2 configs.

the 2nd way is ok too

**Comment by Alexey-T** [comment]
the 'mapping' lexername->langid is OK in 1 file too, no?

**Comment by halfbrained** [comment]
> the 'mapping' lexername->langid is OK in 1 cfg file too, no?

hm... how such a config would look like? I can't see a clear and nice way.

**Comment by Alexey-T** [comment]
{
  "lexers": {
     "onelexer": "id1",
     "twolexer": "id2"
    },
  //rest
}

**Comment by halfbrained** [comment]
yep... going with your format

**Comment by halfbrained** [comment]
new format
``` python
{
    // supported langids
    "langids": ["python"],
    // map additional non-default lexers to langids 
    "lexers": {
    	"Rainbow python": "python"
    },
    // command to start LSP server
    "cmd": ["pyls"]
}
```

**Comment by Alexey-T** [comment]
первый ключ избыточен- можно его получить по всем значениям 'lexers'

**Comment by halfbrained** [comment]
Да, я сначала без первого сделал, но это:
``` python
{
    "langids": ["python"],
    "cmd": ["pyls"]
}
```
лучше этого мне кажется 
``` python
{
    "lexers": {
    	"Python": "python"
    },
    "cmd": ["pyls"]
}
```

кстати оба варианта сейчас работают... так что я могу либо написать в ридми, что 'lexers' и 'langids' взаимозаменяемы, либо убрать 'langids' из примера конфига, и упомянуть отдельно.

**Comment by Alexey-T** [comment]
```
{
    "lexers": {
    	"Python": "python"
    },
    "cmd": ["pyls"]
}
```
это то что надо. потому что тут мы можем указать 2-3 лексера и 2-3 языка сервера

**Comment by halfbrained** [comment]
updated readme, no related code changes

https://github.com/halfbrained/cuda_lsp/commit/9d5419af2d3b3af9bb24f19547aa338eb5b040c6
