### ISSUE TITLE
maybe 'delay' these imports too?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#45]
```
import sys
_plugin_dir = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.join(_plugin_dir, 'lsp_modules'))

import cuda_project_man

from .book import DocBook
```

maybe move them into 'work' function?

ProjMan-- must have! it's slow

**Comment by halfbrained** [comment]
moved cuda_project_man, Docbook; and removed json

Same 3-4ms startup time :) project man loads even when project is not opened and its panel is closed... but maybe it will improve the first start somewhat

**Comment by Alexey-T** [comment]
on 2nd PC: same 18 ms time. no change...

**Comment by halfbrained** [comment]
Now we should make a plugin that will pack all tiny files in one single file, and redirect all file access to that pack so app will start in 10 ms :)

**Comment by Alexey-T** [comment]
ignore my deleted comment - startup time is OK now
