### ISSUE TITLE
readme- mix of tabs and spaces

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#52]
![pp](https://user-images.githubusercontent.com/4154978/114766869-9dd75e00-9d6f-11eb-929d-3e3b8dd704bb.png)

**Comment by Alexey-T** [comment]
![Screenshot from 2021-04-14 23-39-46](https://user-images.githubusercontent.com/4154978/114776054-b5681400-9d7a-11eb-98c6-a53b7512d996.png)

**Comment by halfbrained** [comment]
fixed (should have known there would be a command :) )
