### ISSUE TITLE
document formatting?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#54]
Пи сервер умеет так-
Document Formatting:
https://raw.githubusercontent.com/palantir/python-language-server/develop/resources/document-format.gif

можем сделать?

**Comment by halfbrained** [comment]
можем, даже опции почти все есть
```
/**
* Size of a tab in spaces.
*/
tabSize: uinteger;

/**
* Prefer spaces over tabs.
*/
insertSpaces: boolean;

/**
* Trim trailing whitespace on a line.
*/
trimTrailingWhitespace?: boolean;

/**
* Insert a newline character at the end of the file if one does not exist.
*/
insertFinalNewline?: boolean;

/**
* Trim all newlines after the final newline at the end of the file.
*/
trimFinalNewlines?: boolean;
```

`insertFinalNewline` - у CudaText нету?

**Comment by Alexey-T** [comment]
это ненужные опции,давайте зададим
trimTrailingWhitespace on
insertFinalNewline on
trimFinalNewlines on

**Comment by halfbrained** [comment]
Кроме insertFinalNewline, я думал брать опции из Editor.get_prop, есть причина этого не делать?

(Использовать опции юзера же должно быть предпочтительно?)

> * Size of a tab in spaces. -- PROP_TAB_SIZE
> * Prefer spaces over tabs. -- PROP_TAB_SPACES
> * Trim trailing whitespace on a line. -- PROP_SAVING_TRIM_SPACES
> * Trim all newlines after the final newline at the end of the file. -- PROP_SAVING_TRIM_FINAL_EMPTY_LINES

**Comment by Alexey-T** [comment]
да, согласен, лучше брать PROP_

**Comment by Alexey-T** [comment]
и еще PROP_SAVING_FORCE_FINAL_EOL

**Comment by halfbrained** [comment]
сделал document formatting

посмотрел, pyls  поддерживает и range formatting, наверное тоже пригодится

**Comment by Alexey-T** [comment]
спасибо. :)

**Comment by halfbrained** [comment]
добавил и range formatting
