### ISSUE TITLE
Alternative definitions popup

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#57]
https://www.youtube.com/watch?v=3wUBrW3bsoo
3:48
глава про то как выглядит definition popup- 

- кликабельная ссылка на definition
- правее имя лексера для definition (нужно для многоязыкового файла)
- кликабельные ссылки на ref's

что если сделать это как новый акшен- с новым popup? видимо это сборка разной инфы. может сделать по Alt+hover?

**Comment by Alexey-T** [comment]
и еще там такая иконка ПРАВЕЕ ссылки - квадратик на половину полный. он откроет ссылку в pair editor.

**Comment by halfbrained** [comment]
Можно...

Но может лучше добавить references и остальные функции как кнопки в hover? ("go to definition" там одиноко) И дать конфиг чтобы можно было ненужные убрать оттуда?

**Comment by Alexey-T** [comment]
хорошо, пока давайте так.

**Comment by halfbrained** [comment]
![hint_19](https://user-images.githubusercontent.com/74829192/115009954-84402e80-9eb5-11eb-8d4c-6abaffb9cf6a.png)

statusbar

Я думал показывать тут только поддерживаемые сервером команды... но наверное лучше так?:
* юзер в конфиге указывает нужные команды
* ставить неподдерживаемым командам неактивный вид

**Comment by Alexey-T** [comment]
да, согласен.

**Comment by Alexey-T** [comment]
вижу statusbar не дает ячейкам св-во enabled. но без него разберетесь? там можно ставить любые цвета ячейкам. font color/ bg color.

**Comment by halfbrained** [comment]
Да, разберусь
