### ISSUE TITLE
let's use new API

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#58]
beta is here
http://uvviewsoft.com/c/

let's show tooltip near `(` bracket.
https://wiki.freepascal.org/CudaText_API#msg_status_alt

**Comment by Alexey-T** [comment]
and fix the api= line

**Comment by halfbrained** [comment]
Works:
![hint_ok](https://user-images.githubusercontent.com/74829192/114878654-235b1c80-9e09-11eb-80f4-f04757eb0f7b.png)

... but not on the next line:
![hint_err](https://user-images.githubusercontent.com/74829192/114878692-2eae4800-9e09-11eb-8cd2-90b6378cfa8c.png)

**Comment by Alexey-T** [comment]
that was a bug! fixed the beta. updated

**Comment by halfbrained** [comment]
When that caret is against the closing bracket - popup is always anchored to caret position

**Comment by Alexey-T** [comment]
anchor to `(` works only if caret pos is __inside brackets__, coz is counts all pairs `()`.

**Comment by halfbrained** [comment]
Well yeah, I don't get function call params when i'm outside of `()`; here is the problematic position

![hint_err2](https://user-images.githubusercontent.com/74829192/114905937-3201fd80-9e22-11eb-9611-592dd318338f.png)

**Comment by Alexey-T** [comment]
fixed; beta updated.
