### ISSUE TITLE
new readme.txt

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#60]
[readme.zip](https://github.com/halfbrained/cuda_lsp/files/6325159/readme.zip)

**Comment by Alexey-T** [comment]
fix
[readme.zip](https://github.com/halfbrained/cuda_lsp/files/6325181/readme.zip)

**Comment by Alexey-T** [comment]
fix
[readme.zip](https://github.com/halfbrained/cuda_lsp/files/6325202/readme.zip)

**Comment by halfbrained** [comment]
updated, thanks
