### ISSUE TITLE
server doesn't see that project is opened

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#61]
![Screenshot from 2021-04-16 20-21-55](https://user-images.githubusercontent.com/4154978/115061172-7f00d500-9ef1-11eb-933b-1832460bbd04.png)

это папка плагина html_tooltips добавленная в проект.
"главный файл" проект стоит как `__init__.py`.

из init - goto def - не работает для включенных имен из colorcodes.py.
на скрине имя выделено какое я проверяю.
оно из colorcodes.py.

**Comment by Alexey-T** [comment]
в конфиге менял, не помогло
    "root_dir_source": 1,

**Comment by Alexey-T** [comment]
заработало! после того как задал в proj-man 'reopen on cuda start' и restart.

но почему не работает если сначала открыти питон файл, потом открыли проект proj-man?

**Comment by halfbrained** [comment]
Мне нужно знать папку проэкта во время создания сервера; сейчас я получаю её во время загрузки конфига.

Чтобы было правильно - нужно будет реагировать на смену проэкта (перезапускать сервер)... я на это как-то смотрел и какие-то сложности были... кажется нету ивента для смены проэкта?

**Comment by Alexey-T** [comment]
пока такого ивента нету. может добавить в АПИ ф-цию "послать такой то ивент (например on_project) всем плагинам"?

**Comment by Alexey-T** [comment]
или может так? вы читаете из projMan его global_project_info и смотрите что "проект стал друго"

**Comment by halfbrained** [comment]
я бы ожидал это в `on_state()`, `on_project` тоже подошел бы, таймер бы делать не хотелось.

**Comment by Alexey-T** [comment]
а если сравнивать filename of project (global_project_info) и смотреть что оно изменилось? по скорости не медленно

**Comment by halfbrained** [comment]
C# сервер может 8 сек запускаться, по действию - не получится.

таймер так таймер :)

**Comment by halfbrained** [comment]
Сделал. Перезапускаю серверы если изменилась root dir, учитывая `root_dir_source` опцию

**Comment by Alexey-T** [comment]
а как же #68 ?

**Comment by Alexey-T** [comment]
разве не по ивенту on_state надо перезап.сервер?

**Comment by Alexey-T** [comment]
аа, ОК
