### ISSUE TITLE
smthing broke with Py server

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#67]
plugin: Project Manager, `__init__` file.
для выделенного слова (app_proc) ничего не нахрдит.
в консоли ошибки...
хотя для плага html_tooltips такое же работало вчера

![Screenshot from 2021-04-16 22-36-50](https://user-images.githubusercontent.com/4154978/115075760-3f8fb400-9f04-11eb-8f22-298695f771bd.png)

может серву не нравится imports? без задания папки проекта? тут проект не открыт

**Comment by halfbrained** [comment]
'cudatext.py' должен быть где-то в `sys.path`, а с проэктами я в соседнем issue пока разбираюсь :)

**Comment by Alexey-T** [comment]
cudatext.py - in-memory module, not a file!

**Comment by Alexey-T** [comment]
конечно он в sys.path, по умолчанию Куд добавляет свою папку py в path

**Comment by halfbrained** [comment]
В консоли CudaText я вижу 'py', но в 'env' процесса CudaText - ее нет... Всегда добавлять 'py' серверу или опцию сделать?

**Comment by Alexey-T** [comment]
в env и не думал ее класть. 
можно так*? если файл лежит в подпапки папки 'py' то давать серверу папку 'py'. иначе это не надо

**Comment by Alexey-T** [comment]
это улучшит работу с плагинами!

**Comment by Alexey-T** [comment]
это делать __только для языка питон__

**Comment by halfbrained** [comment]
> можно так*? если файл лежит в подпапки папки 'py' то давать серверу папку 'py'. иначе это не надо

можно, но! :) я запускаю сервер (тут я задаю 'env') питона когда открывается первый Python скрипт... т.е. если первым открыт файл не из папки 'CudaText/py' -> когда я открою файл плагина - у сервера не будет папки 'py'  в 'env'

Опция наверно лучшее решение - по умолчанию отключено - разработчики плагинов просто включат?

**Comment by Alexey-T** [comment]
хорошо, опция. по умоллч.= Выкл.

**Comment by halfbrained** [comment]
добавил: `cudatext_in_py_env`

попутно добавил в конфиг сервера `env_paths` - добавлять пути в переменные окружения процесса сервера... как `PATH`. Для `cudatext_in_py_env` используется `PYTHONPATH`

(`env_paths` - наверное не особо нужна юзерам, поэтому думал добавлю в ридми если когда-то кому-то понадобится?)

**Comment by Alexey-T** [comment]
не понял что это- env_paths.

**Comment by halfbrained** [comment]
`PATH` сервера редактировать, и другие похожие переменные

**Comment by Alexey-T** [comment]
1st post- решено.

**Comment by halfbrained** [comment]
Еще я во время експериментов добавил в 'sansio_lsp_client' поддержку 'WorkFolders' - замена 'rootUri' - папка проэкта.

Позволяет давать больше одной папки проэкта, и уведомлять сервер когда папки меняются... и Python сервер это поддерживает; пока не проверял - на сколько хорошо...

Поэтому думаю: 
1. попробоавть использовать эту функцию вместо перезапуска сервера (как сейчас), если сервер поддерживает.
2. отсылать все nodes проэкта? (не уверен - не знаком с тем как проэкты используются)

**Comment by Alexey-T** [comment]
>попробоавть использовать эту функцию вместо перезапуска сервера (как сейчас), если сервер поддерживает.

тут надо пробовать сервера- хотя бы основные (py, C#, C++)

**Comment by halfbrained** [comment]
> (py, C#, C++)

троица поддерживает

Сервер уведомляет при запуске - поддерживает ли он это. Буду менять рут - если поддерживает, и просто перезапускать - если нет.

**Comment by Alexey-T** [comment]
OK

**Comment by halfbrained** [comment]
приделал смену рут-папки. Проверил в С# и Python
