### ISSUE TITLE
need new option value - root_dir_source

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#69]
example proj
```
{
    "nodes": [
        "/home/user/.config/cudatext/py/cuda_html_tooltips"
    ],
    "mainfile": "/home/user/.config/cudatext/py/cuda_html_tooltips/__init__.py"
}
```
для опции "root_dir_source" надо дать вариант "папка от main file (если не задан main file, делать fallback)"

**Comment by Alexey-T** [comment]
@halfbrained не сложно сделать значение опции?

**Comment by halfbrained** [comment]
>  (если не задан main file, делать fallback)

fallback на какое значение? Я не вижу логической связи между этими тремя значениями... может дать возможность задавать несколько значение?
``` json
"root_dir_source": 0,
// and
"root_dir_source": [0, 1, 2],
```

**Comment by Alexey-T** [comment]
да, так будет лучше всего.

**Comment by halfbrained** [comment]
добавил
