### ISSUE TITLE
can we avoid plugin loading before some work with plugin begins?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#7]
ie work begins

- when I call plugin's commands in menu
- when I call auto-complete, show func-hint, or goto-definition

Plug loads 100+ msec. big.

**Comment by halfbrained** [comment]
I need `on_open()` to start server and show file's analysis (diagnostics), so probably not?

**Comment by Alexey-T** [comment]
can we do slow init of code only when we need to start? ie Python server exists. I open some Ruby file--> LSP is not yet needing slow init. I open TXT file -> same. I open Python file-> do initing

**Comment by halfbrained** [comment]
How can I do that?

I was convinced that I either have `on_open` in 'install.inf' or not.

...if you mean - not to start Python server until Python file is open - it already doesn't. You can check in process manager, or you can run `xxcuda_lsp._langs` in Console to see loaded servers.

**Comment by Alexey-T** [comment]
you can move all 'imports' (of slow libs) + all global objects initing (from that slow libs) into `if` block.

**Comment by halfbrained** [comment]
It mostly works, starts now in 3ms.

A bug: during CudaText startup in `on_open()`: `ed_group()` gives wrong editor (first one it seems)

This code...
``` python
def on_open(self, ed_self):
  group_ed = ed_group(0)
  print(f'on_open: ed_self:{ed_self};   group_ed:{group_ed}')
```
...gives:
![group_ed](https://user-images.githubusercontent.com/74829192/114426719-046b4900-9bc3-11eb-9ff2-1d866f8f07b1.png)

On the screenshot: 'regex' tab is selected, but in log you can see that in `on_open()` 'group_ed` is editor for 'file_mover.py'

Should I make a repro plugin?

**Comment by Alexey-T** [comment]
yes, please.

**Comment by Alexey-T** [comment]
demo is needed, maybe Cud has OK tab's index=0 and gives ok result

**Comment by halfbrained** [comment]
If I can't use `ed_group()` in `on_open()` is there any other way to see if `Editor` is visible. (trying to avoid processing documents that weren't actually opened)

I see that I can use `Editor.get_prop(PROP_ACTIVATION_TIME)` with a timer, but maybe there is a more direct way?

**Comment by Alexey-T** [comment]
- I see that PROP_ACTIVATION_TIME gets 0 for editors which were not activated. yet.
- PROP_INDEX* gets tab index of editor. you can compare it with PROP_INDEX* of active group editor from ed_group(i).

**Comment by halfbrained** [comment]
>     * PROP_INDEX* gets tab index of editor. you can compare it with PROP_INDEX* of active group editor from ed_group(i).

But I can't use `ed_group()` in `on_open()`, and I would like to avoid `timer_proc`

---

A different approach that almost works for me:
1. in `on_open()` if Editor's time is zero - delay it
2. on `APPSTATE_SESSION_LOAD` pick up delayed items

This works on app startup. 

But when I'm switching session with 'Session Manager', in those `on_open()` first tab has non-zero time (not active tab):
```
NOTE: on_open ed_self:<Editor id:4 title:"install.inf" gr:0 tab:0>;  time:26693679
NOTE: on_open ed_self:<Editor id:5 title:"__init__.py" gr:0 tab:1>;  time:0
```
(after that, on 'APPSTATE_SESSION_LOAD' I get expected times)
```
 ----- APPSTATE_SESSION_LOAD
* vis:False for -- <Editor id:4 title:"install.inf" gr:0 tab:0>;    time:0
* vis:True for -- <Editor id:5 title:"__init__.py" gr:0 tab:1>;    time:26693696
```
---

So I have a request: can tabs have zero time during session switch?

**Comment by Alexey-T** [comment]
it's a bad idea to 'force zero times for tabs', in Cud. now activation_time is honest. if 0, tab is not activated.
in session loading you have active 1st tab? then it's honest. 1st tab is active, not the new tabs. (Cud doesn't activate all tabs on session-load)

**Comment by Alexey-T** [comment]
ps. If i force some 'time' to 0, it may regress the work of Tab-switcher, who checks that times.

**Comment by halfbrained** [comment]
Well then it is a bug - it is showing the wrong time :)


In this session: tab-2 `__init__.py` is active (second tab), but tab-1 has time in `on_open()` during session switch... but  when session is finished loading (event 'APPSTATE_SESSION_LOAD') first tab has been reset to zero time
```
NOTE: on_open ed_self:<Editor id:4 title:"install.inf" gr:0 tab:0>;  time:26693679
NOTE: on_open ed_self:<Editor id:5 title:"__init__.py" gr:0 tab:1>;  time:0
 ----- APPSTATE_SESSION_LOAD
* vis:False for -- <Editor id:4 title:"install.inf" gr:0 tab:0>;    time:0
* vis:True for -- <Editor id:5 title:"__init__.py" gr:0 tab:1>;    time:26693696
```

Would you like a repro?

**Comment by Alexey-T** [comment]
session-loading has code
```
    //clear tick values, to CudaExt tab switcher feels good
    //(it shows frames with tick=0 in second listbox)
    for i:= 0 to FrameCount-1 do
    begin
      Frame:= Frames[i];
      if Frame.Visible then
        Frame.ActivationTime:= GetTickCount64
      else
        Frame.ActivationTime:= 0;
    end;
           
```

**Comment by Alexey-T** [comment]
so it was a hack for CudaExt plugin.

**Comment by halfbrained** [comment]
got it, will be using timer_proc

**Comment by halfbrained** [comment]
using timer_proc is a bit difficult... 

so another question: would it be possible in `on_open()` to somehow see if session is currently being loaded? So I could just wait for `APPSTATE_SESSION_LOAD`?

This would be a 100 times better solution :)

**Comment by Alexey-T** [comment]
maybe add the new state APPSTATE_SESSION_LOADING whci means 'session begins to load'?

**Comment by Alexey-T** [comment]
please file a report in Cud issues.

**Comment by halfbrained** [comment]
fixed

![fast_startup](https://user-images.githubusercontent.com/74829192/114587310-34cbe980-9c8e-11eb-8c81-4c60753a7d2c.png)
