### ISSUE TITLE
hover form for simple Int constant

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#70]
дает вот это, а можно ли убрать эту мишуру? я делаю hover для целой константы. MAX_LINES
![Screenshot from 2021-04-17 16-31-10](https://user-images.githubusercontent.com/4154978/115114944-8334fd00-9f9a-11eb-8b99-5f64c6bc673b.png)

**Comment by Alexey-T** [comment]
и тоже самое для строковых констант.

**Comment by Alexey-T** [comment]
интересно как ведут себя Субл и VScode?

**Comment by halfbrained** [comment]
Саблайм тоже показывает информацию о типе. Этот текст - все что я получаю от сервера, так что я даже не могу опцию сделать какую-то.

![subline_int](https://user-images.githubusercontent.com/74829192/115115730-a9f53280-9f9e-11eb-87fc-a42db5c33817.png)
