### ISSUE TITLE
func signature tooltip-- maybe make it wider?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#71]
очень узкое окно-= строки вропятся очень рано, лучше бы пошире окно.
![ooo](https://user-images.githubusercontent.com/4154978/115115158-69e08080-9f9b-11eb-909d-e87910f47a45.png)

**Comment by halfbrained** [comment]
по запятой переношу - каждая переменная на своей строке. Я исправлю перенос по запятой внутри типа (как-то...) - будет достаточно?

**Comment by Alexey-T** [comment]
не переносить по запятой внутри скобок `[]{}` -будет Ок

**Comment by Alexey-T** [comment]
это было решено?

**Comment by halfbrained** [comment]
fixed

![funchint_fixed](https://user-images.githubusercontent.com/74829192/115148172-12a7e200-a067-11eb-9746-76574df55384.png)
