### ISSUE TITLE
suggestion for linting

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#73]
May we add an option "linting" (str)?

- empty str - don't do linting
- if value has 'b' - place bookmarks w/o the line BG color - usefull for user to jump by bookmarks
- if value has 'd' - place gutter-decoration marks (ed.decor)
- if value has 'c' - place colored ed.attr attribs with red underlines ('red'==themed)

**Comment by Alexey-T** [comment]
And

- if value has 'B' (upcase) - place bookmarks with BG color

**Comment by halfbrained** [comment]
Only `ed.attr` left to do, and I think I might have had a misunderstanding

>     * if value has 'b' - place bookmarks w/o the line BG color - usefull for user to jump by bookmarks

Should this have visible icons in the gutter? my understanding - yes => only difference between 'b' and 'c' - lack of hover-text for 'c' ... is this correct?

**Comment by Alexey-T** [comment]
yes, placing bookmarks is call `ed.bookmark()` which can run with BG color or w/o BG color (COLOR_NONE).
it will add an icon. it is custom icon (BOOKMARK_SETUP).

**Comment by halfbrained** [comment]
I just thought you maybe meant:
* 'b' - bookmark for 'go to bookmark' - without an icon (empty icon)
* 'd' - just icons (decor())
* 'bd' - icons with bookmarks

I did everything right :)

**Comment by Alexey-T** [comment]
'b'-- bookmark with BG color == COLOR_NONE
'B'-- same with BG color !=COLOR_NONE ('B' has high proority if both 'b' and 'B' in string)
'c' - color attrs
'd' - decor

maybe allow string to have few chars at once? like 'bdc'.

**Comment by Alexey-T** [comment]
e.g. 'Bc' -- bookmark with color + underline attr.

**Comment by halfbrained** [comment]
> maybe allow string to have few chars at once? like 'bdc'.

That is how I thought you meant :D  

> if value **has** ...

so yes, 'bdc' will be accepted (although here 'd' will be overridden by 'b')

**Comment by Alexey-T** [comment]
yes, 'd' must be overrided by 'b' and 'B', 'b' is overriden by 'B'.

**Comment by halfbrained** [comment]
added

`  "lint_type": "Bc"`
![lint_config](https://user-images.githubusercontent.com/74829192/115226673-3119e600-a118-11eb-8f0b-d97273d44c77.png)

`  "lint_type": "c"`
![line_c](https://user-images.githubusercontent.com/74829192/115226762-47c03d00-a118-11eb-8358-0beccea32335.png)

**Comment by halfbrained** [comment]
One moment, a bug - decor image list seems to be per-editor

**Comment by Alexey-T** [comment]
you chosen 'underline style with curly edges'. why? can we have the style of underline as Int option? with default "- - - - lines'.

**Comment by halfbrained** [comment]
I wanted the 'wave', but chose wrong and didn't notice :D 

Are you sure such a minor thing warrants an option? Easy to do, but I think it will just clutter the config.

**Comment by Alexey-T** [comment]
i think yes-- 4 good styles:

- solid line
- dotted line
- line `- - - - -`
- wave

**Comment by halfbrained** [comment]
![dsah](https://user-images.githubusercontent.com/74829192/115231168-eb601c00-a11d-11eb-9215-89f6d2abd0e5.png)

I think there is something wrong with my dashes :D is this a bug or am I expecting too much from a dash?

`border_down=2`

**Comment by Alexey-T** [comment]
that may be painted by Lazarus and it's OS-specific line, so its OK

**Comment by halfbrained** [comment]
done 

(for now I found another bug in diffs)

**Comment by Alexey-T** [comment]
I cannot find any lint-marks in plugin HTML_Tooltips, do you see them?

**Comment by halfbrained** [comment]
I do. Did you install linter module? `pyflakes`

**Comment by Alexey-T** [comment]
I did not. sorry

**Comment by Alexey-T** [comment]
Is the work slower (Py, C#) when linting is used? if it is, let's turn off option by default.

**Comment by halfbrained** [comment]
Nope, really fast
