### ISSUE TITLE
add to readme

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#74]
добавить для первого параграфа
```
"Hover dialog" feature: dialog appears when you stop moving the mouse cursor, over some
identifier, with Ctrl-key pressed.


Example for Python
------------------
```

**Comment by Alexey-T** [comment]
может для мака уточнить? не помню как там работает 'c' 

    with Ctrl-key pressed (Command-key on macOS).

**Comment by halfbrained** [comment]
> может для мака уточнить? не помню как там работает 'c'

проверил, мне мак дает "с" для Control (но я не уверен - в самой ОС у меня 'Meta' и 'Control' перепутаны :D )

добавил
