### ISSUE TITLE
Server configuration

### ISSUE THREAD

**Issue by halfbrained** [halfbrained/cuda_lsp#75]
It recently came to my attention that servers can be configured by the client ([options example](https://github.com/golang/tools/blob/master/gopls/doc/settings.md)), per-server can be added easily as a "settings" category in 'lsp_*.json'. 

But maybe  there should be a way to configure it per-project? 
* User project properties? Problem - not a json - probably should be same format as per-server options... but probably the best option
* A command like "Configure LSP server for current project", that will create and open a 'lsp_settings.json' file along the project file?

**Comment by Alexey-T** [comment]
because later I will rewrite proj-manager (will make it in pascal, new options file) let's make a new file lsp_settings.json. per your request. file in the same dir as project-file. and a command 'configure lsp server'

**Comment by Alexey-T** [comment]
new suggestion for name-- orig.cuda-proj-lsp .

**Comment by halfbrained** [comment]
added (https://github.com/halfbrained/cuda_lsp/commit/4f1e262604b6b24a8434088f146d159ccbe4c4fb)

**Comment by Alexey-T** [comment]
great, thanks.
