### ISSUE TITLE
Handling server notifications/logs

### ISSUE THREAD

**Issue by halfbrained** [halfbrained/cuda_lsp#76]
I think maybe give each server a separate panel for their outputs? LSP servers give logs, and messages to show in UI, both with severity (log, info, warning, error)

For now I'm putting logs to the Output panel, and messages to the Console, but it would be nice to highlight these properly according to severity; using 'NOTE: ' and '*Error: ' of the Console panel wouldn't look too nice.

**Comment by Alexey-T** [comment]
it is a good idea. maybe give in lsp_*.json the option `"panel": true`
or even `"panel": "error,warning,info,log"` (show only mentioned kinds) ?

**Comment by Alexey-T** [comment]
(the implementaion  of panel-- can be seen in FTP plg.)

**Comment by halfbrained** [comment]
Ok, panel will be 'on' by default, and disabled with `"panel": false` in server or plugin configs.

And severity filter will be in the panel's form or context menu - since user might want to toggle these frequently

**Comment by Alexey-T** [comment]
yes, sounds good.

**Comment by halfbrained** [comment]
Added (https://github.com/halfbrained/cuda_lsp/commit/f63b10b3f3d6a32000ae720edfa1542002c3cc8c)

![log_panel](https://user-images.githubusercontent.com/74829192/119234236-7d9c7b00-bb35-11eb-9f52-9f93f2318764.png)

**Comment by Alexey-T** [comment]
Looks very good! I can publish it after a few days, not now
