### ISSUE TITLE
Add option: format document on save

### ISSUE THREAD

**Issue by halfbrained** [halfbrained/cuda_lsp#77]

**Comment by halfbrained** [comment]
@Alexey-T Is it ok to use `app_idle(True)` in a loop in `on_save_pre()` for a second, while I wait for server to send formatting info?

This approach works splendidly, but I'm not entirely clear on `app_idle` inner workings

**Comment by Alexey-T** [comment]
App_idle calls Lazarus processing of OS messages. so keyb/clicks input it possible. if it works, OK.

**Comment by halfbrained** [comment]
Added, and a few more things

**Comment by Alexey-T** [comment]
Is this stable version, to publish it?

**Comment by halfbrained** [comment]
yes
