### ISSUE TITLE
DialogEmmet 'module'

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#78]

**Comment by Alexey-T** [comment]
In plugin EmmetLite I call autocompletion for line 159
```
            self.dlg = Dial|ogEmmet(do_expand_abbrev, self.insert_text_at_caret)
```
it shows 'DialogEmmet .................. module'. why 'module'?

**Comment by halfbrained** [comment]
It's just guessing I assume.

Probably because of a local import `from .dlg_emmet import...`. You need to point the server to the directory where the target file is -- project directory need to be the directory of the plugin in this case
