### ISSUE TITLE
fixed readme file

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#85]
[readme.zip](https://github.com/halfbrained/cuda_lsp/files/6442476/readme.zip)

also fix trailing char ` in history.txt

**Comment by Alexey-T** [comment]
Readme dont tell __what options__ can we write to .cuda-proj-lsp ! can we have URL to some docs which tells it?

**Comment by halfbrained** [comment]
updated

**Comment by Alexey-T** [comment]
updated text more, sorry
[readme4.zip](https://github.com/halfbrained/cuda_lsp/files/6442888/readme4.zip)

**Comment by halfbrained** [comment]
thanks, updated :)
