### ISSUE TITLE
Cannot move mouse over hover-form

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#89]
plugin code: HTML Tooltips.
hover over `compile` in last line `re.compile(REGEX_ENT, 0)`
form shows, but with __distance__ above name.

![Screenshot from 2021-05-12 23-38-14](https://user-images.githubusercontent.com/4154978/118041349-5991aa80-b37b-11eb-8641-36c6a31e8e63.png)

pic shows that distance is about 10-20 px.
now I move mouse to hover-form and mouse hovers the upper line
`re.compile(REGEX_PIC_CSS, re.I)`
and so hover-form HIDES and SHOWS AGAIN for another line!
(I move mouse with Ctrl pressed)
so I cannot move mouse over hover form!

**Comment by Alexey-T** [comment]
possible solving:
if mouse moves from original hover-form-show-pos (on ".compile") to the hover form,dont trigger the new 'hover'

**Comment by Alexey-T** [comment]
or:
document that mouse must be moved w-out Ctrl to move it over form.

**Comment by halfbrained** [comment]
Removed extra line between hover dialog and target text (my mistake from converting text position to pixels)

And increased cursor move tolerance. 15 px was too little. Works well now.
