### ISSUE TITLE
If possible, add filling of code-tree from LSP server

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#92]
https://github.com/Alexey-T/CudaText/issues/3369#issuecomment-841801712

**Comment by Alexey-T** [comment]
Wiki info on this
https://wiki.lazarus.freepascal.org/CudaText_API#How_plugin_can_fill_code-tree

**Comment by Alexey-T** [comment]
Tree-helper API - https://wiki.lazarus.freepascal.org/CudaText_API#TreeHelpers

**Comment by halfbrained** [comment]
If I understand correctly, the only problem with tree helpers that I see - I can only know: is **currently running lsp-servers** support this functionalty -- so I can't list supported lexers in 'install.inf'

Is there some workaround for this, or should I use code-tree directly?

**Comment by Alexey-T** [comment]
I don't see the workaround
so you have to fill code-tree as here- https://wiki.lazarus.freepascal.org/CudaText_API#How_plugin_can_fill_code-tree

**Comment by halfbrained** [comment]
Well, it works:
<details><summary>testing</summary>  
<img src="https://user-images.githubusercontent.com/74829192/118673757-efa55500-b801-11eb-96f7-c9c4b8bf835a.png"/>
</details>  

Now I would like to clarify a few things... 

1. From the item-types that server can give me, these I ignore:
    
    > PROPERTY
    > FIELD
    > VARIABLE
    > CONSTANT
    > STRING
    > NUMBER
    > BOOLEAN
    > ARRAY
    > OBJECT
    > KEY
    > NULL
    > ENUMMEMBER
    > EVENT
    > OPERATOR
    > TYPEPARAMETER
    
    and these I put in the tree, correct?
    
    > FILE
    > MODULE
    > NAMESPACE
    > PACKAGE
    > CLASS
    > METHOD
    > CONSTRUCTOR
    > ENUM
    > INTERFACE
    > FUNCTION
    > STRUCT

2. Should this feature be enabled by default? And a global+server options to disable? Or maybe only for some lexers, like if writing cuda-lexer is too difficult?

**Comment by Alexey-T** [comment]
>and these I put in the tree, correct?

IMO an option (per server) will be good here (comma-separated str / list of str)

>Should this feature be enabled by default?

no! off by default. it gives the slowdown. option per-server will be ok.

**Comment by halfbrained** [comment]
Added. Off by default, and symbol kinds to show are configured via an option.

**Comment by Alexey-T** [comment]
Great, thanks, and readme is updated too - good.
