### ISSUE TITLE
Test with VSCode CSS server

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#95]
https://github.com/vscode-langservers/vscode-css-languageserver-bin
I ask to test this, it is rather popular server, used in ST3 python package. (Maybe I will do)

if it’s setup is not easy/simple then give the needed info, I will post a wiki topic about this server. 
it's interesting how 1 server can handle 2-4 lexers for us (css scss sass less).
@halfbrained @jairomartineza @miroslavmatas
@ildarkhasanshin @d-mal
( https://wiki.lazarus.freepascal.org/CudaText_plugins#LSP_Client )

**Comment by halfbrained** [comment]
it isn't working at the moment - this server is a bit weird... I'll get right on that :)

**Comment by halfbrained** [comment]
Установка сервера: 
1. скачать архив репозитория [vscode](https://github.com/microsoft/vscode)
2. достать из архива папку `/vscode-main/extensions/css-language-features/server` и перейти в нее.
3. заменить содержимое файла 'tsconfig.json' на:
    ``` json
    {
	    "compilerOptions": {
		    "target": "es2018",
		    "lib": [
			    "es2018"
		    ],
		    "module": "commonjs",
		    "strict": true,
		    "alwaysStrict": true,
		    "noImplicitAny": true,
		    "noImplicitReturns": true,
		    "noImplicitOverride": true,
		    "noUnusedLocals": true,
		    "noUnusedParameters": true,
		    "forceConsistentCasingInFileNames": true,
		    
		    "outDir": "./out"
	    },
      "files": [
          "src/node/cssServerMain.ts"
      ]
    }	
    ```
4. установить зависимости и typescript:
    ``` shell
    # в терминале
    npm install
    npm install typescript
    ```
5. скомпилировать:
    ``` shell
    # в терминале
    npx tsc
    ```

Команда запуска для 'lsp_css.json' будет выглядеть так:
```  json
"cmd_unix": [
    "node",
    // заменить на полный путь к папке 'server'
    ".../server/out/node/cssServerMain.js",
    "--stdio"
]
```

**Comment by Alexey-T** [comment]
Thanks, posted.
