### ISSUE TITLE
options .md file shows 2 'yellow places' in Cudatext

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#96]
![Screenshot from 2021-06-01 16-33-36](https://user-images.githubusercontent.com/4154978/120332292-47aa8400-c2f7-11eb-91c9-691c8c4b9890.png)

**Comment by halfbrained** [comment]
fixed

![optmd](https://user-images.githubusercontent.com/74829192/120334443-4d08ce00-c2f9-11eb-921c-f3fe9a3ace89.png)
