### ISSUE TITLE
here is some interesting post about LSP stuff

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#98]
https://kate-editor.org/post/2021/2021-06-21-dart-support/
maybe you will find smth good for us. :)

**Comment by halfbrained** [comment]
Will syntax highlighting from LSP be useful? Specification doesn't look too bad, but CudaText already has like a billion lexers :), so I thought it is not needed

**Comment by Alexey-T** [comment]
it is not needed.
LSP has another feature though. __semantic__ hilight. the same IDs are colored with single color. Cud users didn't ask it but will be 'nice to have'.

**Comment by Alexey-T** [comment]
(but I think semantic hilight will be slow - Cud will have LOT of ed.attr attribs)

**Comment by halfbrained** [comment]
Hm... the linked post talks about [semantic tokens](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_semanticTokens), it just gives a list of tokens with their types:
```
type
class
enum
interface
struct
typeParameter
parameter
variable
property
enumMember
event
function
method
macro
keyword
modifier
comment
string
number
regexp
operator
```
and a modifiers:
```
declaration
definition
readonly
static
deprecated
abstract
async
modification
documentation
defaultLibrary
```

To me it seems like it is only useful for coloring text ("syntax highlighting", an alternative for lexers), so I'm not sure what this is about:
> semantic hilight. the same IDs are colored with single color

**Comment by Alexey-T** [comment]
so linked post is Not about 'semantic hilite'. good. then we don't need 'simple hilite'.
