### ISSUE TITLE
For Nim?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#99]
linux.org.ru, юзер пишет

LSP Client
Запилите пожалуйста ЛСП для Nim lang из коробки, чтобы попасть в этот список https://github.com/nim-lang/Nim/wiki/Editor-Support а там смотришь и пользователей прибавится. И благодарность от анонимусов будет.
anonymous (07.07.21 11:24:57)

**Comment by halfbrained** [comment]
Работает без проблем

конфиг:
``` json
{
    "name": "nim-lsp",
    "lexers": {
        "Nim": "nim"
    },
    "cmd_unix": [
      "/home/men/.nimble/bin/nimlsp"
    ]
}
```

**Comment by Alexey-T** [comment]
will write that to the WIki. tks.
